### ISSUE TITLE
Create more storage objects in onetime

### ISSUE THREAD

**Issue by juadk** [saltstack-formulas/iscsi-formula#19]
Hi, I wonder if there is a proper way to create more storage_objects in onetime. 
I tried some solutions but all failed, I have this pillar file:

```
iscsi:
  isns:
    enabled: false
  target:
    lio:
      myconf:
        fabric_modules:
          authenticate_target: 'false'
          enforce_discovery_auth: 'false'
          name: "iscsi"
        storage_objects:
          attributes:
            block_size: 512
            emulate_write_cache: 0
            queue_depth: 64
            unmap_granularity: 0
          dev: "/dev/xvdd1"
          name: "sda"
          plugin: "block"
        targets:
          fabric: iscsi
          tpgs:
            attributes:
              authentication: 0
              cache_dynamic_acls: 0
              default_cmdsn_depth: 16
              demo_mode_write_protect: 0
              generate_node_acls: 1
              login_timeout: 15
              netif_timeout: 2
              prod_mode_write_protect: 0
            luns:
              index: 0
              storage_object: "/backstores/block/sda"
            portals:
              ip_address: xxxxxxxxx
              port: 3260
            tag: 1
          wwn: "iqn.1996-04.blabla:01:a66aed20e2f3"
```

I would like to add /dev/xvdd2 ==> sdb ==> lun1 and so one.
Maybe I'm missing something here, do you have an idea?
